### ISSUE TITLE
Create Static Mockups

### ISSUE THREAD

**Issue by EriQ** [EriQ/ConceptForge#10]
- [x] Home Page

- [x] Gallery Page

- [x] Results Page

- [x] Tour Boxes

- [x] Convert to HTML/CSS

**Comment by TimKellyTheMighty** [comment]
Have you seen my pocket?

**Comment by TimKellyTheMighty** [comment]
Working on static mock-ups. Should have them complete by tomorrow.

**Comment by TimKellyTheMighty** [comment]
It's coming together!
