### ISSUE TITLE
Indicate the ability to swipe to see more

### ISSUE THREAD

**Issue by EriQ** [EriQ/ConceptForge#42]
In both the category list and randomizer, it is unclear that there are more items that are not visible. We need to indicate that the user is only seeing part of the options.

**Comment by TimKellyTheMighty** [comment]
Agreed. Is there a way to indicate that without taking away from our minimal element style?

**Comment by EriQ** [comment]
I added a subtle indicator for your approval.

**Comment by TimKellyTheMighty** [comment]
It looks great! Thanks for the quick response!
