### ISSUE TITLE
Create a Gallery Page

### ISSUE THREAD

**Issue by EriQ** [EriQ/ConceptForge#8]
This page will contain the Instagram feed for whatever hashtag we choose to use. 

- [x] Install Instafeed.js

- [x] Create a client id to access images

- [x] Add Page to app to hold feed

- [x] Add link to gallery in header

**Comment by TimKellyTheMighty** [comment]
I'd like to go ahead and use the hashtag #conceptforge since it doesn't seem to be in use. This should make it simple to add to the feed. 
Also a line of text under the header explaining what hashtag to use would probably help first time users know what to do when posting.

**Comment by EriQ** [comment]
Ok. I currently have it using #belguawhale for testing purposes since there is no #ConceptForge yet. I'll change it when I get all of the bugs worked out. 
Did this ever start working for you? You may have to re-download the app.

**Comment by TimKellyTheMighty** [comment]
Still fails to connect to server.

**Comment by EriQ** [comment]
Ok. I'll look into it next week. In the meantime, we need to decide how many images we want to display. I have it set at 30, and the load time is >30s. Perhaps we should limit it to 18? That would give us three pages of images.
