### ISSUE TITLE
Revisions and Edits

### ISSUE THREAD

**Issue by TimKellyTheMighty** [EriQ/ConceptForge#86]
- [x] Padding Under Logo - add more space between icons and icon titles.

- [x] Add Blue To Button Animation Sequences - Make the buttons turn the same blue color as the icon text when pressed. Only the randomize and refresh/back button. Probably a three series animation for "randomize button" from yellow to blue to clear inside.

- [x] Make Corner Logo Icon return to home screen on both pages - This is up to you, but i keep wanting to click on it to go back. Might confuse some people idk.

- [x] Add more leading to "Your Concept Words Are"

- [x] Start Page? - Elizabeth mentioned that their isn't much info on what the app does inside the actual app. Would it be weird to include a welcome page with the logo like on the splash page and some copy about the app and a "Start" button? Open to your ideas and opinions.

**Comment by EriQ** [comment]
I'll get these done asap. None of them should take too long. I will say that I think the welcome page, we should have a checkbox to allow users to skip it.

**Comment by TimKellyTheMighty** [comment]
Copy For Start Page

"Welcome to Concept Forge, the concept generator for creatives! Use this app to create conceptual challenges and practice your creativity."

**Comment by EriQ** [comment]
Finished in merge #88
